version: "3"
services: 
  maven:
    image: maven:3.3-jdk-8
    container_name: maven
    working_dir: /tmp
    command: >
            bash -c "rm -rf App42PaaS-Java-MySQL-Sample; git clone https://github.com/anpolyakov/App42PaaS-Java-MySQL-Sample.git
            && mkdir ${HOME}/ROOT && cp App42PaaS-Java-MySQL-Sample/WebContent/Config.properties ${HOME}/ROOT/Config.properties
            && cd App42PaaS-Java-MySQL-Sample && mvn clean && mvn install && cd ..
            && cp /tmp/App42PaaS-Java-MySQL-Sample/target/App42PaaS-Java-MySQL-Sample-0.0.1-SNAPSHOT.war ."
    volumes:
      - myapp:/tmp/
      - conf:${HOME}
  tomcat:
    image: tomcat:latest
    container_name: tomcat
    links: maven
    volumes: 
      - myapp:/usr/local/tomcat/webapps
      - conf:/usr/local/tomcat
    ports:
      - "8080:8080"
    links:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: lesson12
      MYSQL_USER: user
      MYSQL_PASSWORD: password
volumes:
  myapp:
  conf:
