version: "3.3"
services: 
  maven:
    image: maven:3.3-jdk-8
    container_name: maven
    links:
      - tomcat
  tomcat:
    image: tomcat:latest
    ports:
      - "8080:8080"
    links:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: lesson12
      MYSQL_USER: user
      MYSQL_PASSWORD: password

      

    
